name: Daily Commit Workflow

on:
  schedule:
    # Runs at 12:00 PM (UTC) every day
    - cron: '0 12 * * *'  # Set to a specific hour and minute (UTC time zone)
  workflow_dispatch: # Optional trigger for manual execution

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to access its contents
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Git for committing
    - name: Set up Git configuration
      run: |
        git config --global user.name "23f2002600"
        git config --global user.email "23f2002600@ds.study.iitm.ac.in"

    # Create a file and commit changes (a dummy change for the commit)
    - name: Add a commit (email 23f2002600@ds.study.iitm.ac.in in the name)
      run: |
        echo "Daily commit" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit by 23f2002600@ds.study.iitm.ac.in"

    # Push the commit using the GitHub token
    - name: Push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/23f2002600/TDS_W2.git
        git push
